import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
// import { ThirdwebProvider } from "@thirdweb-dev/react";
import Providers from "./Provider"; // Import your react-query Providers component
import { ThirdwebProvider } from "thirdweb/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SecureID Chain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThirdwebProvider>
          <Providers> {/* Add the Providers component here */}
            <Navbar />
            {children}
          </Providers>
        </ThirdwebProvider>
      </body>
    </html>
  );
}
